copyright: Copyright © 2008-2026 the <a href="https://ts.sch.gr">Ομάδα Τεχνικής Στήριξης</a>
dev_addr: 0.0.0.0:7101
edit_uri: tree/main/docs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      title: Περιεχόμενα σελίδας
plugins:
  - minify:
      minify_html: false
  - search
  - with-pdf:
      author: Έκδοση pdf του https://ts.sch.gr/wiki/windows
      copyright: Copyright © 2008-2026 Τεχνική Στήριξη ΣΕΠΕΗΥ
      cover_title: ΣΕΠΕΗΥ με Windows
      cover_subtitle: Οδηγός εγκατάστασης, διαμόρφωσης & χρήσης
      debug_html: false
      enabled_if_env: ENABLE_PDF_EXPORT
      heading_shift: true
      ordered_chapter_level: 3
      output_path: windows.pdf
      toc_level: 3
      toc_title: Πίνακας περιεχομένων
repo_url: https://github.com/pe86/windows
site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ
site_url: https://ts.sch.gr/wiki/windows
strict: false
theme:
# favicon: favicon.ico
  features:
    - todo-navigation.instant
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
  language: el
  # Enable `locale: el` when it becomes available
  # https://www.mkdocs.org/user-guide/choosing-your-theme/#mkdocs-locale
  # locale: el
  logo: stylesheets/ts-logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα
  titles_only: true
nav:
  - index.md
  - Αυτόνομες Εγκαταστάσεις:
      - Windows 11:
        - client/index.md
        - client/requirements.md
        - client/compatibility.md
        - Εγκατάσταση:
          - client/installation/index.md
          - client/installation/rufus.md
          - client/installation/manual/index.md
          - client/installation/unattended/index.md
        - client/basic-settings/index.md
        - Μετέπειτα Ενέργειες:
          - client/software.md
          - client/peripherals.md
          - client/create-users.md
      - Windows Server 2022:
        - server/index.md
        - server/requirements.md
        - server/compatibility.md
        - Εγκατάσταση:
          - server/installation/index.md
          - server/installation/manual/index.md
          - server/installation/unattended/index.md
        - server/basic-settings/index.md
        - Μετέπειτα Ενέργειες:
          - server/software.md
          - server/peripherals.md
          - server/create-users.md
  - Client Server Αρχιτεκτονική:
        - client-server/index.md
        - Περιγραφή Αρχιτεκτονικής:
          - client-server/architecture.md
          - client-server/advantages.md
          - client-server/disadvantages.md
          - client-server/requirements.md
        - Οδηγίες εγκατάστασης:
          - client-server/server-setup-dc/index.md
          - client-server/domain-policy/index.md
          - client-server/client-domain-join/index.md
          - client-server/create-users.md
        - Μετέπειτα ενέργειες:
          - client-server/guides.md
          - client-server/peripherals.md
        - Για προχωρημένους:
          - client-server/advanced.md
  - Centralized Computing Αρχιτεκτονική:
        - server-based/index.md
        - Περιγραφή Αρχιτεκτονικής:
          - server-based/architecture.md
          - server-based/advantages.md
          - server-based/disadvantages.md
          - server-based/requirements.md
        - Οδηγίες εγκατάστασης:
          - server-based/server-setup-rdsh/index.md
          - server-based/client-connect-rdsh.md
          - server-based/create-users.md
        - Μετέπειτα ενέργειες:
          - server-based/guides.md
          - server-based/peripherals.md
        - Για προχωρημένους:
          - server-based/advanced.md
          - server-based/additional-software.md
          - server-based/rdsh-customization.md
          - server-based/rds-license-setup.md
  - Προσθήκη λογισμικού:
      - software/index.md
      - Για αρχάριους:
        - software/7zip.md
        - software/infrarecorder.md
        - software/sumatrapdf.md
        - software/irfanview.md
        - software/firefox.md
        - software/chrome.md
        - software/palemoon.md
        - software/vlc.md
        - software/flash.md
        - software/java.md
        - software/libreoffice.md
        - software/msoffice.md
        - software/gimp.md
        - software/audacity.md
        - software/blender.md
        - software/snappy-driver.md
        - software/sch-scripts.md
      - Για προχωρημένους:
        - software/advanced/index.md
        - software/advanced/veyon.md
        - software/advanced/virtualbox.md
        - software/advanced/remote-access.md
        - software/advanced/updates-share.md
        - software/advanced/squid.md
